apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag
  template:
    metadata:
      labels:
        app: rag
    spec:
      containers:
      - name: rag-container
        image: rag-app
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
               name: rag-secret
               key: GROQ_API_KEY
