name: RAG Pipeline

on:  
  workflow_dispatch:

env:
   IMAGE_NAME: rag-app

jobs:
  deploy:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v4
      # Start Minikube (if not running)
      - name: Start Minikube
        run: |
          minikube status || minikube start --memory=4096 --cpus=2 --driver=docker

      # Build INSIDE Minikube (IMPORTANT)
      - name: Build Image in Minikube
        run: |
          eval $(minikube docker-env)
          docker build -t rag-app ./RAG_chatbot

      # Create Secret
      - name: Create K8s Secret
        run: |
          kubectl create secret generic rag-secret \
          --from-literal=GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
          --dry-run=client -o yaml | kubectl apply -f -

      # Deploy
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f RAG_chatbot/deployment.yml
          kubectl apply -f RAG_chatbot/service.yml

      # Verify
      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get svc
